service: notes-app-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-2

  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-2:*:*"

functions:
  createMur:
    handler: function/createMur.main
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam

  getMur:
    handler: function/getMur.main
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
          authorizer: aws_iam

  list:
    handler: function/listUserMurs.main
    events:
      - http:
          path: notes
          method: get
          cors: true
          authorizer: aws_iam

  listAllMur:
    handler: function/listAllMur.main
    events:
      - http:
          path: notes
          method: get
          cors: true
          authorizer: aws_iam

  update:
    handler: update.main
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true
          authorizer: aws_iam

  deleteMur:
    handler: function/deleteMur.main
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true
          authorizer: aws_iam

  # addSchemaToMur: AS A POST /mur/:id/schema
  #* GetSCHEMA: AS A GET mur/:id/schema/:id | HANDLE THE GET SHARE REQUEST
  #* GetSHARE: AS A GET mur/:id/schema/:id/share/:id
  #* BuyShare: AS A PUT  mur/:id/schema/:id/share/:id | sellingSHare in part of buying share
  # Update share: AS A PATCH mur/:id
